
import re

def convert_tsql_to_postgres(input_file, output_file):
    with open(input_file, 'r') as f:
        sql = f.read()

    # Removes
    sql = re.sub(r'SET ANSI_NULLS ON', '', sql)
    sql = re.sub(r'SET QUOTED_IDENTIFIER ON', '', sql)
    sql = re.sub(r'GO', ';', sql) # Replace GO with ; for safety, or just remove if unrelated
    sql = re.sub(r'TEXTIMAGE_ON \[PRIMARY\]', '', sql)
    sql = re.sub(r'ON \[PRIMARY\]', '', sql)
    sql = re.sub(r'WITH \(PAD_INDEX = .*?\)', '', sql)
    sql = re.sub(r'/\*{6}.*?\*{6}/', '', sql) # Remove huge comments headers

    # Replacements
    sql = sql.replace('[dbo].', '') # Remove dbo schema
    sql = sql.replace('[', '"').replace(']', '"') # Square brackets to double quotes
    sql = sql.replace('nvarchar(max)', 'text')
    sql = sql.replace('nvarchar', 'varchar')
    sql = sql.replace('uniqueidentifier', 'uuid')
    sql = sql.replace('bit', 'boolean')
    sql = sql.replace('datetime2', 'timestamp')
    sql = sql.replace('datetimeoffset', 'timestamptz')
    sql = sql.replace('float', 'double precision') # Postgres float is real/double
    sql = sql.replace('IDENTITY(1,1)', 'GENERATED BY DEFAULT AS IDENTITY')
    
    # Clean up multiple newlines
    sql = re.sub(r'\n\s*\n', '\n\n', sql)

    # basic clustered primary key fix
    # T-SQL: PRIMARY KEY CLUSTERED ([Id] ASC)
    # PG: PRIMARY KEY ("Id")
    sql = re.sub(r'CONSTRAINT "PK_.*?" PRIMARY KEY CLUSTERED\s*\(\s*"Id" ASC\s*\)', 'PRIMARY KEY ("Id")', sql)
    
    # Fix other PKs that might be composite
    # CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY CLUSTERED ( "UserId" ASC, "RoleId" ASC )
    # This regex is tricky. Let's do a generic one.
    # We can just remove CLUSTERED and ASC
    sql = sql.replace('CLUSTERED', '')
    sql = sql.replace('ASC', '')

    with open(output_file, 'w') as f:
        f.write(sql)

if __name__ == "__main__":
    convert_tsql_to_postgres('schema.sql', 'schema_pg.sql')
