

;

;
CREATE TABLE "Actors"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "ActorUsers"(
	"Id" "uuid" NOT NULL,
	"ActorId" "uuid" NOT NULL,
	"UserId" "varchar"(450) NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "AspNetRoleClaims"(
	"Id" "int" GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"RoleId" "varchar"(450) NOT NULL,
	"ClaimType" "varchar"(max) NULL,
	"ClaimValue" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "AspNetRoles"(
	"Id" "varchar"(450) NOT NULL,
	"Name" "varchar"(256) NULL,
	"NormalizedName" "varchar"(256) NULL,
	"ConcurrencyStamp" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "AspNetUserClaims"(
	"Id" "int" GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"UserId" "varchar"(450) NOT NULL,
	"ClaimType" "varchar"(max) NULL,
	"ClaimValue" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "AspNetUserLogins"(
	"LoginProvider" "varchar"(450) NOT NULL,
	"ProviderKey" "varchar"(450) NOT NULL,
	"ProviderDisplayName" "varchar"(max) NULL,
	"UserId" "varchar"(450) NOT NULL,
 CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY  
(
	"LoginProvider" ,
	"ProviderKey" 
) 
)  
;

;

;
CREATE TABLE "AspNetUserRoles"(
	"UserId" "varchar"(450) NOT NULL,
	"RoleId" "varchar"(450) NOT NULL,
 CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY  
(
	"UserId" ,
	"RoleId" 
) 
) 
;

;

;
CREATE TABLE "AspNetUsers"(
	"Id" "varchar"(450) NOT NULL,
	"UserName" "varchar"(256) NULL,
	"NormalizedUserName" "varchar"(256) NULL,
	"Email" "varchar"(256) NULL,
	"NormalizedEmail" "varchar"(256) NULL,
	"EmailConfirmed" "boolean" NOT NULL,
	"PasswordHash" "varchar"(max) NULL,
	"SecurityStamp" "varchar"(max) NULL,
	"ConcurrencyStamp" "varchar"(max) NULL,
	"PhoneNumber" "varchar"(max) NULL,
	"PhoneNumberConfirmed" "boolean" NOT NULL,
	"TwoFactorEnabled" "boolean" NOT NULL,
	"LockoutEnd" "timestamptz"(7) NULL,
	"LockoutEnabled" "boolean" NOT NULL,
	"AccessFailedCount" "int" NOT NULL,
	"DepartmentId" "uuid" NULL,
	"DesignationId" "uuid" NULL,
	"FirstName" "varchar"(512) NULL,
	"Gender" "int" NOT NULL,
	"LastName" "varchar"(512) NULL,
	"Phone" "varchar"(max) NULL,
	"ProfilePicture" "varchar"(max) NULL,
	"SupervisorId" "varchar"(450) NULL,
	"SupplierPersonId" "uuid" NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "AspNetUserTokens"(
	"UserId" "varchar"(450) NOT NULL,
	"LoginProvider" "varchar"(450) NOT NULL,
	"Name" "varchar"(450) NOT NULL,
	"Value" "varchar"(max) NULL,
 CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY  
(
	"UserId" ,
	"LoginProvider" ,
	"Name" 
) 
)  
;

;

;
CREATE TABLE "BrandProductSizeMLs"(
	"Id" "uuid" NOT NULL,
	"ProductId" "uuid" NOT NULL,
	"SizeMLId" "uuid" NOT NULL,
	"BrandId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Brands"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Categories"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Commands"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Countries"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Departments"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Designations"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "DesignLists"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "DirectSchemaInstances"(
	"Id" "uuid" NOT NULL,
	"SchemaId" "uuid" NOT NULL,
	"UserId" "uuid" NOT NULL,
	"RequesterUserId" "uuid" NOT NULL,
	"FormValueId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"HasEnded" "boolean" NOT NULL,
	"IsCancelled" "boolean" NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Fields"(
	"Id" "uuid" NOT NULL,
	"Name" "varchar"(max) NOT NULL,
	"Type" "int" NOT NULL,
	"Pattern" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"NameAr" "varchar"(max) NOT NULL,
	"PredefinedValues" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "FormFields"(
	"Id" "uuid" NOT NULL,
	"IsRequired" "boolean" NOT NULL,
	"SortIndex" "int" NOT NULL,
	"FormId" "uuid" NOT NULL,
	"FieldId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "FormFieldValues"(
	"Id" "uuid" NOT NULL,
	"Value" "varchar"(max) NULL,
	"FormValueId" "uuid" NOT NULL,
	"FormFieldId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Forms"(
	"Id" "uuid" NOT NULL,
	"Name" "varchar"(max) NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"NameAr" "varchar"(max) NOT NULL,
	"ParentId" "uuid" NULL,
	"IsSubForm" "boolean" NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "FormValueAttachments"(
	"Id" "uuid" NOT NULL,
	"FormValueId" "uuid" NULL,
	"FormId" "uuid" NOT NULL,
	"Name" "varchar"(max) NOT NULL,
	"Length" "bigint" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"AttachmentId" "uuid" NOT NULL,
	"FilePath" "varchar"(max) NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "FormValues"(
	"Id" "uuid" NOT NULL,
	"FormId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "GroupNames"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Notifications"(
	"Id" "uuid" NOT NULL,
	"NotificationType" "int" NOT NULL,
	"Payload" "varchar"(max) NOT NULL,
	"CreatedAt" "timestamp"(7) NOT NULL,
	"IsRead" "boolean" NOT NULL,
	"UserId" "varchar"(450) NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "NotificationTokens"(
	"Id" "uuid" NOT NULL,
	"Token" "varchar"(max) NOT NULL,
	"AppUserId" "varchar"(450) NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"DeviceId" "varchar"(450) NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "People"(
	"Id" "uuid" NOT NULL,
	"FirstName" "varchar"(max) NOT NULL,
	"LastName" "varchar"(max) NOT NULL,
	"Mobile" "varchar"(max) NOT NULL,
	"Email" "varchar"(max) NOT NULL,
	"Position" "int" NULL,
	"AddressId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"IsDefault" "boolean" NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "ProductionLines"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"CategoryId" "uuid" NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Products"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "ProjectIssues"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(max) NOT NULL,
	"Description" "varchar"(max) NULL,
	"OwnerId" "varchar"(450) NOT NULL,
	"AssignToId" "varchar"(450) NOT NULL,
	"IssueStatus" "int" NOT NULL,
	"IssuePriority" "int" NOT NULL,
	"IssueDate" "timestamp"(7) NULL,
	"DueDate" "timestamp"(7) NULL,
	"ClosedDate" "timestamp"(7) NULL,
	"SolutionPlan" "varchar"(max) NULL,
	"ProjectId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"IsSolved" "boolean" NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "ProjectRisks"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(max) NOT NULL,
	"Description" "varchar"(max) NULL,
	"OwnerId" "varchar"(450) NOT NULL,
	"ApprovedById" "varchar"(450) NOT NULL,
	"RiskStatus" "int" NOT NULL,
	"RiskProbability" "int" NOT NULL,
	"RiskImpact" "int" NOT NULL,
	"RiskPriority" "int" NOT NULL,
	"RiskResponse" "int" NOT NULL,
	"RiskDate" "timestamp"(7) NULL,
	"ResponsePlan" "varchar"(max) NULL,
	"ContingencyPlan" "varchar"(max) NULL,
	"ProjectId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Projects"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"StartDate" "timestamp"(7) NOT NULL,
	"OwnerId" "varchar"(450) NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"SavingStatus" "int" NOT NULL,
	"ProductionLineId" "uuid" NOT NULL,
	"BrandProductSizeMlId" "uuid" NOT NULL,
	"BrandProductSizeMlCode" "varchar"(max) NULL,
	"Status" "int" NOT NULL,
	"Quantity" "int" NOT NULL,
	"ChatId" "uuid" NULL,
	"ProjectType" "int" NOT NULL,
	"IsStockUpdated" "boolean" NOT NULL,
	"ConsultantId" "uuid" NULL,
	"ContractorId" "uuid" NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "projectStatusLogs"(
	"Id" "uuid" NOT NULL,
	"ProjectId" "uuid" NOT NULL,
	"Date" "timestamp"(7) NOT NULL,
	"Ideal" "double precision" NOT NULL,
	"Remaining" "double precision" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "ProjectTags"(
	"Id" "uuid" NOT NULL,
	"ProjectId" "uuid" NOT NULL,
	"TagId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "ProjectTasks"(
	"Id" "uuid" NOT NULL,
	"Status" "int" NOT NULL,
	"AssignedToId" "uuid" NULL,
	"ApprovalById" "uuid" NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(450) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(450) NULL,
	"AcutualDateEnd" "timestamp"(7) NULL,
	"AcutualDateStart" "timestamp"(7) NULL,
	"Description" "varchar"(max) NULL,
	"ParentId" "uuid" NULL,
	"ProjectId" "uuid" NOT NULL,
	"ScheduledDateStart" "timestamp"(7) NOT NULL,
	"ScheduledlDateEnd" "timestamp"(7) NOT NULL,
	"Title" "varchar"(max) NOT NULL,
	"TaskNr" "int" GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Progress" "double precision" NOT NULL,
	"TaskOrder" "int" NULL,
	"IsCloseWithSimilarTag" "boolean" NOT NULL,
	"SortIndex" "double precision" NULL,
	"OutlineLevel" "int" NULL,
	"OutlineNumber" "varchar"(max) NULL,
	"IsSummary" "boolean" NOT NULL,
	"Duration" "double precision" NULL,
	"Weight" "double precision" NULL,
	"IsPrimaryTask" "boolean" NOT NULL,
	"PrimaryTaskId" "uuid" NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "QuotationRequestComments"(
	"Id" "uuid" NOT NULL,
	"QuotationRequestDetailId" "uuid" NOT NULL,
	"HtmlBody" "varchar"(max) NOT NULL,
	"UserId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"FromSupplier" "boolean" NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "QuotationRequestDetails"(
	"Id" "uuid" NOT NULL,
	"QuotationRequestId" "uuid" NOT NULL,
	"ComponentDetailKey" "varchar"(max) NOT NULL,
	"ComponentDetailValue" "varchar"(max) NULL,
	"ComponentDetailType" "varchar"(max) NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "QuotationRequestHistories"(
	"Id" "uuid" NOT NULL,
	"QuotationRequestDetailId" "uuid" NOT NULL,
	"SupplierValue" "varchar"(max) NULL,
	"Price" "double precision" NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"QuotationActionType" "int" NOT NULL,
	"QuotationRequestSupplierId" "uuid" NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "QuotationRequests"(
	"Id" "uuid" NOT NULL,
	"ComponentId" "uuid" NOT NULL,
	"ComponentName" "varchar"(max) NOT NULL,
	"ComponentDescription" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"Code" "varchar"(max) NOT NULL,
	"ProjectId" "uuid" NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "QuotationRequestSuppliers"(
	"Id" "uuid" NOT NULL,
	"SupplierId" "uuid" NOT NULL,
	"QuotationRequestId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"ReplyDate" "timestamp"(7) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "QuotationSupplierReplyDetails"(
	"Id" "uuid" NOT NULL,
	"QuotationDetailId" "uuid" NOT NULL,
	"QuotationSupplierId" "uuid" NOT NULL,
	"SupplierValue" "varchar"(max) NOT NULL,
	"Price" "double precision" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "RealTimeConnections"(
	"Id" "uuid" NOT NULL,
	"ConnectionId" "varchar"(max) NOT NULL,
	"UserAgent" "varchar"(max) NULL,
	"Connected" "boolean" NOT NULL,
	"UserId" "varchar"(450) NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"ConnectedAt" "timestamp"(7) NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "RefreshTokens"(
	"Id" "uuid" NOT NULL,
	"UserId" "varchar"(450) NULL,
	"Token" "varchar"(512) NOT NULL,
	"Expires" "timestamp"(7) NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedByIp" "varchar"(50) NOT NULL,
	"Revoked" "timestamp"(7) NULL,
	"RevokedByIp" "varchar"(50) NULL,
	"ReplacedByToken" "varchar"(512) NULL,
	"ReasonRevoked" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "RiskProposedSolutions"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(max) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsAcceptedSolution" "boolean" NOT NULL,
	"ProjectRiskId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "SchemaInstanceHistories"(
	"Id" "uuid" NOT NULL,
	"SchemaId" "uuid" NOT NULL,
	"CommandName" "varchar"(max) NOT NULL,
	"SchemaInstanceId" "uuid" NULL,
	"DirectSchemaInstanceId" "uuid" NULL,
	"FromActorId" "uuid" NULL,
	"ToActorId" "uuid" NULL,
	"FromUserId" "uuid" NULL,
	"ToUserId" "uuid" NULL,
	"Order" "int" NOT NULL,
	"Comment" "varchar"(max) NOT NULL,
	"ActionDate" "timestamp"(7) NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"FormValueId" "uuid" NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "SchemaInstances"(
	"Id" "uuid" NOT NULL,
	"SchemaId" "uuid" NOT NULL,
	"CurrentSchemaStepId" "uuid" NOT NULL,
	"RequesterUserId" "uuid" NOT NULL,
	"FormValueId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(450) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"CurrentStepFormId" "uuid" NULL,
	"IsChangeRequestStep" "boolean" NOT NULL,
	"HasEnded" "boolean" NOT NULL,
	"IsCancelled" "boolean" NOT NULL,
	"ProjectId" "uuid" NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "SchemaPriorityLevels"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Schemas"(
	"Id" "uuid" NOT NULL,
	"Name" "varchar"(max) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDirect" "boolean" NOT NULL,
	"PriorityLevelId" "uuid" NOT NULL,
	"FormId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"SupplierId" "uuid" NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "SchemaStepCommands"(
	"Id" "uuid" NOT NULL,
	"SchemaStepId" "uuid" NOT NULL,
	"CommandId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "SchemaSteps"(
	"Id" "uuid" NOT NULL,
	"SchemaId" "uuid" NOT NULL,
	"ActorId" "uuid" NOT NULL,
	"StepId" "uuid" NOT NULL,
	"StatusId" "uuid" NOT NULL,
	"Order" "int" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"FormId" "uuid" NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "SizeMLs"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Status"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Steps"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsFinal" "boolean" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "SupplierAddresses"(
	"Id" "uuid" NOT NULL,
	"Country" "varchar"(max) NULL,
	"City" "varchar"(max) NULL,
	"Street" "varchar"(max) NULL,
	"ZipCode" "varchar"(max) NULL,
	"POBox" "varchar"(max) NULL,
	"Tel" "varchar"(max) NULL,
	"Mobile" "varchar"(max) NULL,
	"Fax" "varchar"(max) NULL,
	"WebSiteUrl" "varchar"(max) NULL,
	"AddressType" "int" NULL,
	"SupplierId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Suppliers"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(max) NOT NULL,
	"Description" "varchar"(max) NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"Currency" "varchar"(max) NOT NULL,
	"MinOrder" "int" NULL,
	"Type" "int" NOT NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "Tags"(
	"Id" "uuid" NOT NULL,
	"Name" "varchar"(512) NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "TaskAttachments"(
	"Id" "uuid" NOT NULL,
	"Name" "varchar"(max) NOT NULL,
	"Length" "bigint" NOT NULL,
	"ProjectTaskId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(450) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "TaskComments"(
	"Id" "uuid" NOT NULL,
	"HtmlBody" "varchar"(max) NOT NULL,
	"TaskId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "TaskHistories"(
	"Id" "uuid" NOT NULL,
	"ProjectTaskId" "uuid" NOT NULL,
	"ChangedValue" "int" NOT NULL,
	"OldValue" "varchar"(max) NULL,
	"NewValue" "varchar"(max) NULL,
	"UserId" "varchar"(450) NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"ActionDescription" "int" NOT NULL,
	"AttachmentId" "uuid" NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "TaskPredecessors"(
	"Id" "uuid" NOT NULL,
	"TaskId" "uuid" NOT NULL,
	"SuccessorId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"ProjectId" "uuid" NULL,
 PRIMARY KEY ("Id") 
)  
;

;

;
CREATE TABLE "ToDos"(
	"Id" "uuid" NOT NULL,
	"Title" "varchar"(512) NOT NULL,
	"Description" "varchar"(max) NULL,
	"Action" "int" NOT NULL,
	"Checked" "boolean" NOT NULL,
	"ProjectTaskId" "uuid" NOT NULL,
	"IsDeleted" "boolean" NOT NULL,
	"Created" "timestamp"(7) NOT NULL,
	"CreatedBy" "varchar"(max) NULL,
	"LastModified" "timestamp"(7) NULL,
	"LastModifiedBy" "varchar"(max) NULL,
	"Data" "varchar"(max) NULL,
 PRIMARY KEY ("Id") 
)  
;
ALTER TABLE "AspNetUsers" ADD  DEFAULT ((0)) FOR "Gender"
;
ALTER TABLE "DirectSchemaInstances" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "HasEnded"
;
ALTER TABLE "DirectSchemaInstances" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "IsCancelled"
;
ALTER TABLE "Fields" ADD  DEFAULT (N'') FOR "NameAr"
;
ALTER TABLE "Forms" ADD  DEFAULT (N'') FOR "NameAr"
;
ALTER TABLE "Forms" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "IsSubForm"
;
ALTER TABLE "FormValueAttachments" ADD  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR "AttachmentId"
;
ALTER TABLE "FormValueAttachments" ADD  DEFAULT (N'') FOR "FilePath"
;
ALTER TABLE "NotificationTokens" ADD  DEFAULT (N'') FOR "DeviceId"
;
ALTER TABLE "People" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "IsDefault"
;
ALTER TABLE "ProductionLines" ADD  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR "CategoryId"
;
ALTER TABLE "ProjectIssues" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "IsSolved"
;
ALTER TABLE "Projects" ADD  DEFAULT ((0)) FOR "SavingStatus"
;
ALTER TABLE "Projects" ADD  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR "ProductionLineId"
;
ALTER TABLE "Projects" ADD  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR "BrandProductSizeMlId"
;
ALTER TABLE "Projects" ADD  DEFAULT ((0)) FOR "Status"
;
ALTER TABLE "Projects" ADD  DEFAULT ((1)) FOR "Quantity"
;
ALTER TABLE "Projects" ADD  DEFAULT ((0)) FOR "ProjectType"
;
ALTER TABLE "Projects" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "IsStockUpdated"
;
ALTER TABLE "ProjectTasks" ADD  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR "ProjectId"
;
ALTER TABLE "ProjectTasks" ADD  DEFAULT ('0001-01-01T00:00:00.0000000') FOR "ScheduledDateStart"
;
ALTER TABLE "ProjectTasks" ADD  DEFAULT ('0001-01-01T00:00:00.0000000') FOR "ScheduledlDateEnd"
;
ALTER TABLE "ProjectTasks" ADD  DEFAULT (N'') FOR "Title"
;
ALTER TABLE "ProjectTasks" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "IsCloseWithSimilarTag"
;
ALTER TABLE "ProjectTasks" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "IsSummary"
;
ALTER TABLE "ProjectTasks" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "IsPrimaryTask"
;
ALTER TABLE "QuotationRequestComments" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "FromSupplier"
;
ALTER TABLE "QuotationRequestHistories" ADD  DEFAULT ((0)) FOR "QuotationActionType"
;
ALTER TABLE "QuotationRequests" ADD  DEFAULT (N'') FOR "Code"
;
ALTER TABLE "QuotationRequests" ADD  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR "ProjectId"
;
ALTER TABLE "RealTimeConnections" ADD  DEFAULT ('0001-01-01T00:00:00.0000000') FOR "ConnectedAt"
;
ALTER TABLE "SchemaInstances" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "IsChangeRequestStep"
;
ALTER TABLE "SchemaInstances" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "HasEnded"
;
ALTER TABLE "SchemaInstances" ADD  DEFAULT (CONVERT("boolean",(0))) FOR "IsCancelled"
;
ALTER TABLE "Suppliers" ADD  DEFAULT (N'SAR') FOR "Currency"
;
ALTER TABLE "Suppliers" ADD  DEFAULT ((0)) FOR "Type"
;
ALTER TABLE "TaskHistories" ADD  DEFAULT ((0)) FOR "ActionDescription"
;
ALTER TABLE "ActorUsers"  WITH CHECK ADD  CONSTRAINT "FK_ActorUsers_Actors_ActorId" FOREIGN KEY("ActorId")
REFERENCES "Actors" ("Id")
ON DELETE CADE
;
ALTER TABLE "ActorUsers" CHECK CONSTRAINT "FK_ActorUsers_Actors_ActorId"
;
ALTER TABLE "ActorUsers"  WITH CHECK ADD  CONSTRAINT "FK_ActorUsers_AspNetUsers_UserId" FOREIGN KEY("UserId")
REFERENCES "AspNetUsers" ("Id")
ON DELETE CADE
;
ALTER TABLE "ActorUsers" CHECK CONSTRAINT "FK_ActorUsers_AspNetUsers_UserId"
;
ALTER TABLE "AspNetRoleClaims"  WITH CHECK ADD  CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY("RoleId")
REFERENCES "AspNetRoles" ("Id")
ON DELETE CADE
;
ALTER TABLE "AspNetRoleClaims" CHECK CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
;
ALTER TABLE "AspNetUserClaims"  WITH CHECK ADD  CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY("UserId")
REFERENCES "AspNetUsers" ("Id")
ON DELETE CADE
;
ALTER TABLE "AspNetUserClaims" CHECK CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
;
ALTER TABLE "AspNetUserLogins"  WITH CHECK ADD  CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY("UserId")
REFERENCES "AspNetUsers" ("Id")
ON DELETE CADE
;
ALTER TABLE "AspNetUserLogins" CHECK CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
;
ALTER TABLE "AspNetUserRoles"  WITH CHECK ADD  CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY("RoleId")
REFERENCES "AspNetRoles" ("Id")
ON DELETE CADE
;
ALTER TABLE "AspNetUserRoles" CHECK CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
;
ALTER TABLE "AspNetUserRoles"  WITH CHECK ADD  CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY("UserId")
REFERENCES "AspNetUsers" ("Id")
ON DELETE CADE
;
ALTER TABLE "AspNetUserRoles" CHECK CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
;
ALTER TABLE "AspNetUsers"  WITH CHECK ADD  CONSTRAINT "FK_AspNetUsers_AspNetUsers_SupervisorId" FOREIGN KEY("SupervisorId")
REFERENCES "AspNetUsers" ("Id")
;
ALTER TABLE "AspNetUsers" CHECK CONSTRAINT "FK_AspNetUsers_AspNetUsers_SupervisorId"
;
ALTER TABLE "AspNetUsers"  WITH CHECK ADD  CONSTRAINT "FK_AspNetUsers_Departments_DepartmentId" FOREIGN KEY("DepartmentId")
REFERENCES "Departments" ("Id")
;
ALTER TABLE "AspNetUsers" CHECK CONSTRAINT "FK_AspNetUsers_Departments_DepartmentId"
;
ALTER TABLE "AspNetUsers"  WITH CHECK ADD  CONSTRAINT "FK_AspNetUsers_Designations_DesignationId" FOREIGN KEY("DesignationId")
REFERENCES "Designations" ("Id")
;
ALTER TABLE "AspNetUsers" CHECK CONSTRAINT "FK_AspNetUsers_Designations_DesignationId"
;
ALTER TABLE "AspNetUsers"  WITH CHECK ADD  CONSTRAINT "FK_AspNetUsers_People_SupplierPersonId" FOREIGN KEY("SupplierPersonId")
REFERENCES "People" ("Id")
;
ALTER TABLE "AspNetUsers" CHECK CONSTRAINT "FK_AspNetUsers_People_SupplierPersonId"
;
ALTER TABLE "AspNetUserTokens"  WITH CHECK ADD  CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY("UserId")
REFERENCES "AspNetUsers" ("Id")
ON DELETE CADE
;
ALTER TABLE "AspNetUserTokens" CHECK CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
;
ALTER TABLE "BrandProductSizeMLs"  WITH CHECK ADD  CONSTRAINT "FK_BrandProductSizeMLs_Brands_BrandId" FOREIGN KEY("BrandId")
REFERENCES "Brands" ("Id")
ON DELETE CADE
;
ALTER TABLE "BrandProductSizeMLs" CHECK CONSTRAINT "FK_BrandProductSizeMLs_Brands_BrandId"
;
ALTER TABLE "BrandProductSizeMLs"  WITH CHECK ADD  CONSTRAINT "FK_BrandProductSizeMLs_Products_ProductId" FOREIGN KEY("ProductId")
REFERENCES "Products" ("Id")
ON DELETE CADE
;
ALTER TABLE "BrandProductSizeMLs" CHECK CONSTRAINT "FK_BrandProductSizeMLs_Products_ProductId"
;
ALTER TABLE "BrandProductSizeMLs"  WITH CHECK ADD  CONSTRAINT "FK_BrandProductSizeMLs_SizeMLs_SizeMLId" FOREIGN KEY("SizeMLId")
REFERENCES "SizeMLs" ("Id")
ON DELETE CADE
;
ALTER TABLE "BrandProductSizeMLs" CHECK CONSTRAINT "FK_BrandProductSizeMLs_SizeMLs_SizeMLId"
;
ALTER TABLE "DirectSchemaInstances"  WITH CHECK ADD  CONSTRAINT "FK_DirectSchemaInstances_Schemas_SchemaId" FOREIGN KEY("SchemaId")
REFERENCES "Schemas" ("Id")
ON DELETE CADE
;
ALTER TABLE "DirectSchemaInstances" CHECK CONSTRAINT "FK_DirectSchemaInstances_Schemas_SchemaId"
;
ALTER TABLE "FormFields"  WITH CHECK ADD  CONSTRAINT "FK_FormFields_Fields_FieldId" FOREIGN KEY("FieldId")
REFERENCES "Fields" ("Id")
ON DELETE CADE
;
ALTER TABLE "FormFields" CHECK CONSTRAINT "FK_FormFields_Fields_FieldId"
;
ALTER TABLE "FormFields"  WITH CHECK ADD  CONSTRAINT "FK_FormFields_Forms_FormId" FOREIGN KEY("FormId")
REFERENCES "Forms" ("Id")
ON DELETE CADE
;
ALTER TABLE "FormFields" CHECK CONSTRAINT "FK_FormFields_Forms_FormId"
;
ALTER TABLE "FormFieldValues"  WITH CHECK ADD  CONSTRAINT "FK_FormFieldValues_FormFields_FormFieldId" FOREIGN KEY("FormFieldId")
REFERENCES "FormFields" ("Id")
ON DELETE CADE
;
ALTER TABLE "FormFieldValues" CHECK CONSTRAINT "FK_FormFieldValues_FormFields_FormFieldId"
;
ALTER TABLE "FormFieldValues"  WITH CHECK ADD  CONSTRAINT "FK_FormFieldValues_FormValues_FormValueId" FOREIGN KEY("FormValueId")
REFERENCES "FormValues" ("Id")
;
ALTER TABLE "FormFieldValues" CHECK CONSTRAINT "FK_FormFieldValues_FormValues_FormValueId"
;
ALTER TABLE "Forms"  WITH CHECK ADD  CONSTRAINT "FK_Forms_Forms_ParentId" FOREIGN KEY("ParentId")
REFERENCES "Forms" ("Id")
;
ALTER TABLE "Forms" CHECK CONSTRAINT "FK_Forms_Forms_ParentId"
;
ALTER TABLE "FormValues"  WITH CHECK ADD  CONSTRAINT "FK_FormValues_Forms_FormId" FOREIGN KEY("FormId")
REFERENCES "Forms" ("Id")
ON DELETE CADE
;
ALTER TABLE "FormValues" CHECK CONSTRAINT "FK_FormValues_Forms_FormId"
;
ALTER TABLE "Notifications"  WITH CHECK ADD  CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY("UserId")
REFERENCES "AspNetUsers" ("Id")
ON DELETE CADE
;
ALTER TABLE "Notifications" CHECK CONSTRAINT "FK_Notifications_AspNetUsers_UserId"
;
ALTER TABLE "NotificationTokens"  WITH CHECK ADD  CONSTRAINT "FK_NotificationTokens_AspNetUsers_AppUserId" FOREIGN KEY("AppUserId")
REFERENCES "AspNetUsers" ("Id")
ON DELETE CADE
;
ALTER TABLE "NotificationTokens" CHECK CONSTRAINT "FK_NotificationTokens_AspNetUsers_AppUserId"
;
ALTER TABLE "People"  WITH CHECK ADD  CONSTRAINT "FK_People_SupplierAddresses_AddressId" FOREIGN KEY("AddressId")
REFERENCES "SupplierAddresses" ("Id")
ON DELETE CADE
;
ALTER TABLE "People" CHECK CONSTRAINT "FK_People_SupplierAddresses_AddressId"
;
ALTER TABLE "ProductionLines"  WITH CHECK ADD  CONSTRAINT "FK_ProductionLines_Categories_CategoryId" FOREIGN KEY("CategoryId")
REFERENCES "Categories" ("Id")
ON DELETE CADE
;
ALTER TABLE "ProductionLines" CHECK CONSTRAINT "FK_ProductionLines_Categories_CategoryId"
;
ALTER TABLE "ProjectIssues"  WITH CHECK ADD  CONSTRAINT "FK_ProjectIssues_AspNetUsers_AssignToId" FOREIGN KEY("AssignToId")
REFERENCES "AspNetUsers" ("Id")
;
ALTER TABLE "ProjectIssues" CHECK CONSTRAINT "FK_ProjectIssues_AspNetUsers_AssignToId"
;
ALTER TABLE "ProjectIssues"  WITH CHECK ADD  CONSTRAINT "FK_ProjectIssues_AspNetUsers_OwnerId" FOREIGN KEY("OwnerId")
REFERENCES "AspNetUsers" ("Id")
;
ALTER TABLE "ProjectIssues" CHECK CONSTRAINT "FK_ProjectIssues_AspNetUsers_OwnerId"
;
ALTER TABLE "ProjectIssues"  WITH CHECK ADD  CONSTRAINT "FK_ProjectIssues_Projects_ProjectId" FOREIGN KEY("ProjectId")
REFERENCES "Projects" ("Id")
ON DELETE CADE
;
ALTER TABLE "ProjectIssues" CHECK CONSTRAINT "FK_ProjectIssues_Projects_ProjectId"
;
ALTER TABLE "ProjectRisks"  WITH CHECK ADD  CONSTRAINT "FK_ProjectRisks_AspNetUsers_ApprovedById" FOREIGN KEY("ApprovedById")
REFERENCES "AspNetUsers" ("Id")
;
ALTER TABLE "ProjectRisks" CHECK CONSTRAINT "FK_ProjectRisks_AspNetUsers_ApprovedById"
;
ALTER TABLE "ProjectRisks"  WITH CHECK ADD  CONSTRAINT "FK_ProjectRisks_AspNetUsers_OwnerId" FOREIGN KEY("OwnerId")
REFERENCES "AspNetUsers" ("Id")
;
ALTER TABLE "ProjectRisks" CHECK CONSTRAINT "FK_ProjectRisks_AspNetUsers_OwnerId"
;
ALTER TABLE "ProjectRisks"  WITH CHECK ADD  CONSTRAINT "FK_ProjectRisks_Projects_ProjectId" FOREIGN KEY("ProjectId")
REFERENCES "Projects" ("Id")
ON DELETE CADE
;
ALTER TABLE "ProjectRisks" CHECK CONSTRAINT "FK_ProjectRisks_Projects_ProjectId"
;
ALTER TABLE "Projects"  WITH CHECK ADD  CONSTRAINT "FK_Projects_AspNetUsers_OwnerId" FOREIGN KEY("OwnerId")
REFERENCES "AspNetUsers" ("Id")
ON DELETE CADE
;
ALTER TABLE "Projects" CHECK CONSTRAINT "FK_Projects_AspNetUsers_OwnerId"
;
ALTER TABLE "Projects"  WITH CHECK ADD  CONSTRAINT "FK_Projects_BrandProductSizeMLs_BrandProductSizeMlId" FOREIGN KEY("BrandProductSizeMlId")
REFERENCES "BrandProductSizeMLs" ("Id")
ON DELETE CADE
;
ALTER TABLE "Projects" CHECK CONSTRAINT "FK_Projects_BrandProductSizeMLs_BrandProductSizeMlId"
;
ALTER TABLE "Projects"  WITH CHECK ADD  CONSTRAINT "FK_Projects_ProductionLines_ProductionLineId" FOREIGN KEY("ProductionLineId")
REFERENCES "ProductionLines" ("Id")
ON DELETE CADE
;
ALTER TABLE "Projects" CHECK CONSTRAINT "FK_Projects_ProductionLines_ProductionLineId"
;
ALTER TABLE "Projects"  WITH CHECK ADD  CONSTRAINT "FK_Projects_Suppliers_ConsultantId" FOREIGN KEY("ConsultantId")
REFERENCES "Suppliers" ("Id")
;
ALTER TABLE "Projects" CHECK CONSTRAINT "FK_Projects_Suppliers_ConsultantId"
;
ALTER TABLE "Projects"  WITH CHECK ADD  CONSTRAINT "FK_Projects_Suppliers_ContractorId" FOREIGN KEY("ContractorId")
REFERENCES "Suppliers" ("Id")
;
ALTER TABLE "Projects" CHECK CONSTRAINT "FK_Projects_Suppliers_ContractorId"
;
ALTER TABLE "ProjectTags"  WITH CHECK ADD  CONSTRAINT "FK_ProjectTags_Projects_ProjectId" FOREIGN KEY("ProjectId")
REFERENCES "Projects" ("Id")
ON DELETE CADE
;
ALTER TABLE "ProjectTags" CHECK CONSTRAINT "FK_ProjectTags_Projects_ProjectId"
;
ALTER TABLE "ProjectTags"  WITH CHECK ADD  CONSTRAINT "FK_ProjectTags_Tags_TagId" FOREIGN KEY("TagId")
REFERENCES "Tags" ("Id")
ON DELETE CADE
;
ALTER TABLE "ProjectTags" CHECK CONSTRAINT "FK_ProjectTags_Tags_TagId"
;
ALTER TABLE "ProjectTasks"  WITH CHECK ADD  CONSTRAINT "FK_ProjectTasks_AspNetUsers_CreatedBy" FOREIGN KEY("CreatedBy")
REFERENCES "AspNetUsers" ("Id")
;
ALTER TABLE "ProjectTasks" CHECK CONSTRAINT "FK_ProjectTasks_AspNetUsers_CreatedBy"
;
ALTER TABLE "ProjectTasks"  WITH CHECK ADD  CONSTRAINT "FK_ProjectTasks_AspNetUsers_LastModifiedBy" FOREIGN KEY("LastModifiedBy")
REFERENCES "AspNetUsers" ("Id")
;
ALTER TABLE "ProjectTasks" CHECK CONSTRAINT "FK_ProjectTasks_AspNetUsers_LastModifiedBy"
;
ALTER TABLE "ProjectTasks"  WITH CHECK ADD  CONSTRAINT "FK_ProjectTasks_Projects_ProjectId" FOREIGN KEY("ProjectId")
REFERENCES "Projects" ("Id")
ON DELETE CADE
;
ALTER TABLE "ProjectTasks" CHECK CONSTRAINT "FK_ProjectTasks_Projects_ProjectId"
;
ALTER TABLE "QuotationRequestComments"  WITH CHECK ADD  CONSTRAINT "FK_QuotationRequestComments_QuotationRequestDetails_QuotationRequestDetailId" FOREIGN KEY("QuotationRequestDetailId")
REFERENCES "QuotationRequestDetails" ("Id")
ON DELETE CADE
;
ALTER TABLE "QuotationRequestComments" CHECK CONSTRAINT "FK_QuotationRequestComments_QuotationRequestDetails_QuotationRequestDetailId"
;
ALTER TABLE "QuotationRequestDetails"  WITH CHECK ADD  CONSTRAINT "FK_QuotationRequestDetails_QuotationRequests_QuotationRequestId" FOREIGN KEY("QuotationRequestId")
REFERENCES "QuotationRequests" ("Id")
ON DELETE CADE
;
ALTER TABLE "QuotationRequestDetails" CHECK CONSTRAINT "FK_QuotationRequestDetails_QuotationRequests_QuotationRequestId"
;
ALTER TABLE "QuotationRequestHistories"  WITH CHECK ADD  CONSTRAINT "FK_QuotationRequestHistories_QuotationRequestDetails_QuotationRequestDetailId" FOREIGN KEY("QuotationRequestDetailId")
REFERENCES "QuotationRequestDetails" ("Id")
ON DELETE CADE
;
ALTER TABLE "QuotationRequestHistories" CHECK CONSTRAINT "FK_QuotationRequestHistories_QuotationRequestDetails_QuotationRequestDetailId"
;
ALTER TABLE "QuotationRequestHistories"  WITH CHECK ADD  CONSTRAINT "FK_QuotationRequestHistories_QuotationRequestSuppliers_QuotationRequestSupplierId" FOREIGN KEY("QuotationRequestSupplierId")
REFERENCES "QuotationRequestSuppliers" ("Id")
;
ALTER TABLE "QuotationRequestHistories" CHECK CONSTRAINT "FK_QuotationRequestHistories_QuotationRequestSuppliers_QuotationRequestSupplierId"
;
ALTER TABLE "QuotationRequests"  WITH CHECK ADD  CONSTRAINT "FK_QuotationRequests_Projects_ProjectId" FOREIGN KEY("ProjectId")
REFERENCES "Projects" ("Id")
ON DELETE CADE
;
ALTER TABLE "QuotationRequests" CHECK CONSTRAINT "FK_QuotationRequests_Projects_ProjectId"
;
ALTER TABLE "QuotationRequestSuppliers"  WITH CHECK ADD  CONSTRAINT "FK_QuotationRequestSuppliers_QuotationRequests_QuotationRequestId" FOREIGN KEY("QuotationRequestId")
REFERENCES "QuotationRequests" ("Id")
ON DELETE CADE
;
ALTER TABLE "QuotationRequestSuppliers" CHECK CONSTRAINT "FK_QuotationRequestSuppliers_QuotationRequests_QuotationRequestId"
;
ALTER TABLE "QuotationRequestSuppliers"  WITH CHECK ADD  CONSTRAINT "FK_QuotationRequestSuppliers_Suppliers_SupplierId" FOREIGN KEY("SupplierId")
REFERENCES "Suppliers" ("Id")
ON DELETE CADE
;
ALTER TABLE "QuotationRequestSuppliers" CHECK CONSTRAINT "FK_QuotationRequestSuppliers_Suppliers_SupplierId"
;
ALTER TABLE "QuotationSupplierReplyDetails"  WITH CHECK ADD  CONSTRAINT "FK_QuotationSupplierReplyDetails_QuotationRequestSuppliers_QuotationSupplierId" FOREIGN KEY("QuotationSupplierId")
REFERENCES "QuotationRequestSuppliers" ("Id")
ON DELETE CADE
;
ALTER TABLE "QuotationSupplierReplyDetails" CHECK CONSTRAINT "FK_QuotationSupplierReplyDetails_QuotationRequestSuppliers_QuotationSupplierId"
;
ALTER TABLE "RealTimeConnections"  WITH CHECK ADD  CONSTRAINT "FK_RealTimeConnections_AspNetUsers_UserId" FOREIGN KEY("UserId")
REFERENCES "AspNetUsers" ("Id")
ON DELETE CADE
;
ALTER TABLE "RealTimeConnections" CHECK CONSTRAINT "FK_RealTimeConnections_AspNetUsers_UserId"
;
ALTER TABLE "RefreshTokens"  WITH CHECK ADD  CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY("UserId")
REFERENCES "AspNetUsers" ("Id")
;
ALTER TABLE "RefreshTokens" CHECK CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId"
;
ALTER TABLE "RiskProposedSolutions"  WITH CHECK ADD  CONSTRAINT "FK_RiskProposedSolutions_ProjectRisks_ProjectRiskId" FOREIGN KEY("ProjectRiskId")
REFERENCES "ProjectRisks" ("Id")
ON DELETE CADE
;
ALTER TABLE "RiskProposedSolutions" CHECK CONSTRAINT "FK_RiskProposedSolutions_ProjectRisks_ProjectRiskId"
;
ALTER TABLE "SchemaInstances"  WITH CHECK ADD  CONSTRAINT "FK_SchemaInstances_AspNetUsers_CreatedBy" FOREIGN KEY("CreatedBy")
REFERENCES "AspNetUsers" ("Id")
;
ALTER TABLE "SchemaInstances" CHECK CONSTRAINT "FK_SchemaInstances_AspNetUsers_CreatedBy"
;
ALTER TABLE "SchemaInstances"  WITH CHECK ADD  CONSTRAINT "FK_SchemaInstances_Projects_ProjectId" FOREIGN KEY("ProjectId")
REFERENCES "Projects" ("Id")
;
ALTER TABLE "SchemaInstances" CHECK CONSTRAINT "FK_SchemaInstances_Projects_ProjectId"
;
ALTER TABLE "SchemaInstances"  WITH CHECK ADD  CONSTRAINT "FK_SchemaInstances_Schemas_SchemaId" FOREIGN KEY("SchemaId")
REFERENCES "Schemas" ("Id")
ON DELETE CADE
;
ALTER TABLE "SchemaInstances" CHECK CONSTRAINT "FK_SchemaInstances_Schemas_SchemaId"
;
ALTER TABLE "SchemaInstances"  WITH CHECK ADD  CONSTRAINT "FK_SchemaInstances_SchemaSteps_CurrentSchemaStepId" FOREIGN KEY("CurrentSchemaStepId")
REFERENCES "SchemaSteps" ("Id")
;
ALTER TABLE "SchemaInstances" CHECK CONSTRAINT "FK_SchemaInstances_SchemaSteps_CurrentSchemaStepId"
;
ALTER TABLE "Schemas"  WITH CHECK ADD  CONSTRAINT "FK_Schemas_SchemaPriorityLevels_PriorityLevelId" FOREIGN KEY("PriorityLevelId")
REFERENCES "SchemaPriorityLevels" ("Id")
ON DELETE CADE
;
ALTER TABLE "Schemas" CHECK CONSTRAINT "FK_Schemas_SchemaPriorityLevels_PriorityLevelId"
;
ALTER TABLE "Schemas"  WITH CHECK ADD  CONSTRAINT "FK_Schemas_Suppliers_SupplierId" FOREIGN KEY("SupplierId")
REFERENCES "Suppliers" ("Id")
;
ALTER TABLE "Schemas" CHECK CONSTRAINT "FK_Schemas_Suppliers_SupplierId"
;
ALTER TABLE "SchemaStepCommands"  WITH CHECK ADD  CONSTRAINT "FK_SchemaStepCommands_Commands_CommandId" FOREIGN KEY("CommandId")
REFERENCES "Commands" ("Id")
ON DELETE CADE
;
ALTER TABLE "SchemaStepCommands" CHECK CONSTRAINT "FK_SchemaStepCommands_Commands_CommandId"
;
ALTER TABLE "SchemaStepCommands"  WITH CHECK ADD  CONSTRAINT "FK_SchemaStepCommands_SchemaSteps_SchemaStepId" FOREIGN KEY("SchemaStepId")
REFERENCES "SchemaSteps" ("Id")
ON DELETE CADE
;
ALTER TABLE "SchemaStepCommands" CHECK CONSTRAINT "FK_SchemaStepCommands_SchemaSteps_SchemaStepId"
;
ALTER TABLE "SchemaSteps"  WITH CHECK ADD  CONSTRAINT "FK_SchemaSteps_Actors_ActorId" FOREIGN KEY("ActorId")
REFERENCES "Actors" ("Id")
ON DELETE CADE
;
ALTER TABLE "SchemaSteps" CHECK CONSTRAINT "FK_SchemaSteps_Actors_ActorId"
;
ALTER TABLE "SchemaSteps"  WITH CHECK ADD  CONSTRAINT "FK_SchemaSteps_Forms_FormId" FOREIGN KEY("FormId")
REFERENCES "Forms" ("Id")
;
ALTER TABLE "SchemaSteps" CHECK CONSTRAINT "FK_SchemaSteps_Forms_FormId"
;
ALTER TABLE "SchemaSteps"  WITH CHECK ADD  CONSTRAINT "FK_SchemaSteps_Schemas_SchemaId" FOREIGN KEY("SchemaId")
REFERENCES "Schemas" ("Id")
ON DELETE CADE
;
ALTER TABLE "SchemaSteps" CHECK CONSTRAINT "FK_SchemaSteps_Schemas_SchemaId"
;
ALTER TABLE "SchemaSteps"  WITH CHECK ADD  CONSTRAINT "FK_SchemaSteps_Status_StatusId" FOREIGN KEY("StatusId")
REFERENCES "Status" ("Id")
ON DELETE CADE
;
ALTER TABLE "SchemaSteps" CHECK CONSTRAINT "FK_SchemaSteps_Status_StatusId"
;
ALTER TABLE "SchemaSteps"  WITH CHECK ADD  CONSTRAINT "FK_SchemaSteps_Steps_StepId" FOREIGN KEY("StepId")
REFERENCES "Steps" ("Id")
ON DELETE CADE
;
ALTER TABLE "SchemaSteps" CHECK CONSTRAINT "FK_SchemaSteps_Steps_StepId"
;
ALTER TABLE "SupplierAddresses"  WITH CHECK ADD  CONSTRAINT "FK_SupplierAddresses_Suppliers_SupplierId" FOREIGN KEY("SupplierId")
REFERENCES "Suppliers" ("Id")
ON DELETE CADE
;
ALTER TABLE "SupplierAddresses" CHECK CONSTRAINT "FK_SupplierAddresses_Suppliers_SupplierId"
;
ALTER TABLE "TaskAttachments"  WITH CHECK ADD  CONSTRAINT "FK_TaskAttachments_AspNetUsers_CreatedBy" FOREIGN KEY("CreatedBy")
REFERENCES "AspNetUsers" ("Id")
;
ALTER TABLE "TaskAttachments" CHECK CONSTRAINT "FK_TaskAttachments_AspNetUsers_CreatedBy"
;
ALTER TABLE "TaskAttachments"  WITH CHECK ADD  CONSTRAINT "FK_TaskAttachments_ProjectTasks_ProjectTaskId" FOREIGN KEY("ProjectTaskId")
REFERENCES "ProjectTasks" ("Id")
ON DELETE CADE
;
ALTER TABLE "TaskAttachments" CHECK CONSTRAINT "FK_TaskAttachments_ProjectTasks_ProjectTaskId"
;
ALTER TABLE "TaskComments"  WITH CHECK ADD  CONSTRAINT "FK_TaskComments_ProjectTasks_TaskId" FOREIGN KEY("TaskId")
REFERENCES "ProjectTasks" ("Id")
ON DELETE CADE
;
ALTER TABLE "TaskComments" CHECK CONSTRAINT "FK_TaskComments_ProjectTasks_TaskId"
;
ALTER TABLE "TaskHistories"  WITH CHECK ADD  CONSTRAINT "FK_TaskHistories_AspNetUsers_UserId" FOREIGN KEY("UserId")
REFERENCES "AspNetUsers" ("Id")
;
ALTER TABLE "TaskHistories" CHECK CONSTRAINT "FK_TaskHistories_AspNetUsers_UserId"
;
ALTER TABLE "TaskHistories"  WITH CHECK ADD  CONSTRAINT "FK_TaskHistories_ProjectTasks_ProjectTaskId" FOREIGN KEY("ProjectTaskId")
REFERENCES "ProjectTasks" ("Id")
ON DELETE CADE
;
ALTER TABLE "TaskHistories" CHECK CONSTRAINT "FK_TaskHistories_ProjectTasks_ProjectTaskId"
;
ALTER TABLE "ToDos"  WITH CHECK ADD  CONSTRAINT "FK_ToDos_ProjectTasks_ProjectTaskId" FOREIGN KEY("ProjectTaskId")
REFERENCES "ProjectTasks" ("Id")
ON DELETE CADE
;
ALTER TABLE "ToDos" CHECK CONSTRAINT "FK_ToDos_ProjectTasks_ProjectTaskId"
;
